# Always review the official build instructions before updating:
# https://wiki.qt.io/PySide2_GettingStarted#Building_PySide2

FROM centos:7

RUN yum install -y epel-release && \
    yum install -y deltarpm && \
    yum groupinstall "Development Tools" -y && \
    yum install -y clang && \
    yum install -y mesa-libGL-devel && \
    yum install -y fontconfig freetype freetype-devel fontconfig-devel libstdc++ && \
    yum install -y python-libs python-devel python-pip && \
    yum install -y https://centos7.iuscommunity.org/ius-release.rpm && \
    yum --enablerepo=ius-archive install -y python35u-libs python35u-devel python35u-pip && \
    yum --enablerepo=ius-archive install -y python36u-libs python36u-devel python36u-pip && \
    yum install -y libxslt libxml2 libxml2-devel libxslt-devel cmake3 openssl && \
    yum install -y which curl p7zip

WORKDIR /workdir

# Clang environment variables in accordance with https://wiki.qt.io/PySide2_GettingStarted
ENV CC="/usr/bin/clang"
ENV CXX="/usr/bin/clang++"

ADD qt-installer-5.6.3-noninteractive.qs /tmp
ADD qt-installer-5.9.3-noninteractive.qs /tmp

# Qt 5.6
RUN curl -L -o /tmp/qt-installer.run https://download.qt.io/archive/qt/5.6/5.6.3/qt-opensource-linux-x64-5.6.3.run && \
    chmod +x /tmp/*.run && \
    /tmp/qt-installer.run --script /tmp/qt-installer-5.6.3-noninteractive.qs -platform minimal && \
    rm -rf /tmp/qt-installer.run

# Qt 5.9
RUN curl -L -o /tmp/qt-installer.run https://download.qt.io/archive/qt/5.9/5.9.3/qt-opensource-linux-x64-5.9.3.run && \
    chmod +x /tmp/*.run && \
    /tmp/qt-installer.run --script /tmp/qt-installer-5.9.3-noninteractive.qs -platform minimal && \
    rm -rf /tmp/qt-installer.run

# Libclang (Qt 5.9 only)
RUN curl -L -o /tmp/libclang.7z http://download.qt.io/development_releases/prebuilt/libclang/libclang-release_39-linux-Rhel7.2-gcc5.3-x86_64.7z && \
    7za x /tmp/libclang.7z -o${HOME}/libclang_release_39 && \
    rm -rf /tmp/libclang.7z
ENV LLVM_INSTALL_DIR="/root/libclang_release_39/libclang"

# Pip requirements
RUN /usr/bin/pip install wheel && \
    /usr/bin/pip3.5 install wheel && \
    /usr/bin/pip3.6 install wheel
