version: 2

clone_pyside_repo: &clone_pyside_repo
  run:
    name: Clone pyside-setup
    command: |
      git clone --recursive --branch $PYSIDE_BRANCH https://code.qt.io/pyside/pyside-setup.git

versions_summary: &versions_summary
  run:
    name: Versions summary
    command: |
      git --git-dir pyside-setup/.git log -n 1
      $CI_PY --version
      $CI_PIP --version
      cmake3 --version
      git --version
      clang --version
      $HOME/Qt-$QT_VER/$QT_VER/gcc_64/bin/qmake --version

build_pyside2: &build_pyside2
  run:
    name: Build PySide2
    command: |
      $CI_PY pyside-setup/setup.py bdist_wheel --ignore-git --standalone --no-examples --qmake=$HOME/Qt-$QT_VER/$QT_VER/gcc_64/bin/qmake --cmake=$CI_CMAKE --jobs=3

jobs:
  centos7-py27-qt5.6.3:
    docker:
      - image: fredrikaverpil/pyside2-linux:centos7
    environment:
      - CI_PY: /usr/bin/python
      - CI_PIP: /usr/bin/pip
      - CI_CMAKE: /usr/bin/cmake3
      - PYSIDE_BRANCH: 5.6
      - QT_VER: 5.6.3
    working_directory: /workdir
    steps:
      - checkout
      - <<: *clone_pyside_repo
      - <<: *versions_summary
      - <<: *build_pyside2
      - store_artifacts:
          path: pyside-setup/dist
      - save_cache:
          key: pyside-setup/dist-{{ .Branch }}
          paths:
            - pyside-setup/dist

  centos7-py35-qt5.6.3:
    docker:
      - image: fredrikaverpil/pyside2-linux:centos7
    environment:
      - CI_PY: /usr/bin/python3.5
      - CI_PIP: /usr/bin/pip3.5
      - CI_CMAKE: /usr/bin/cmake3
      - PYSIDE_BRANCH: 5.6
      - QT_VER: 5.6.3
    working_directory: /workdir
    steps:
      - checkout
      - <<: *clone_pyside_repo
      - <<: *versions_summary
      - <<: *build_pyside2
      - store_artifacts:
          path: pyside-setup/dist
      - save_cache:
          key: pyside-setup/dist-{{ .Branch }}
          paths:
            - pyside-setup/dist

  centos7-py36-qt5.6.3:
    docker:
      - image: fredrikaverpil/pyside2-linux:centos7
    environment:
      - CI_PY: /usr/bin/python3.6
      - CI_PIP: /usr/bin/pip3.6
      - CI_CMAKE: /usr/bin/cmake3
      - PYSIDE_BRANCH: 5.6
      - QT_VER: 5.6.3
    working_directory: /workdir
    steps:
      - checkout
      - <<: *clone_pyside_repo
      - <<: *versions_summary
      - <<: *build_pyside2
      - store_artifacts:
          path: pyside-setup/dist
      - save_cache:
          key: pyside-setup/dist-{{ .Branch }}
          paths:
            - pyside-setup/dist

  deploy:
    docker:
      - image: centos:7
    working_directory: /workdir
    steps:
      - run: ls -alh
      - restore_cache:
          key: pyside-setup/dist-{{ .Branch }}
      - run: ls -alh
      - run: ls -alh pyside-setup/dist
      - run: yum install -y wget unzip
      - run: wget https://github.com/tcnksm/ghr/releases/download/v0.5.4/ghr_v0.5.4_linux_amd64.zip
      - run: unzip ghr_v0.5.4_linux_amd64.zip
      # - run: ./ghr --help

# workflows:
#   version: 2
#   build-deploy:
#     jobs:
#       - centos7-py27-qt5.6.3
#       - centos7-py35-qt5.6.3
#       - centos7-py36-qt5.6.3
#       - deploy:
#           requires:
#             - centos7-py27-qt5.6.3
#             - centos7-py35-qt5.6.3
#             - centos7-py36-qt5.6.3
#           filters:
#             branches:
#               only: master
